version: '3.4'

services:
  mycloudproject:
    image: ${DOCKER_REGISTRY-}mycloudproject
    container_name: mycloudproject
    build:
      context: .
      dockerfile: MyCloudProject/Dockerfile
    environment:
      "LD_LIBRARY_PATH": "/usr/lib"
